# Generated by Django 3.2.5 on 2022-04-05 18:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0003_auto_20220405_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forum',
            new_name='Ad',
        ),
    ]
